# Generated by Django 5.2.1 on 2025-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('repair', 'Ремонт'), ('purchase', 'Покупка'), ('expense', 'Расход')], max_length=20, verbose_name='Тип заявки')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Username')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения Telegram')),
                ('telegram_thread_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID топика (thread)')),
                ('subdivision', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('site', models.CharField(max_length=100, verbose_name='Участок (Объект)')),
                ('equipment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Оборудование (если ремонт)')),
                ('purchase_description', models.TextField(blank=True, null=True, verbose_name='Описание покупки / расхода')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма заявки (сомони)')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Утвердил')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('authorized_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Разрешил')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата разрешения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
